create database MIGRUPOT2;-- CREAR BASE DE DATOS
USE MIGRUPOT2; -- UTILIZAR MI BASE DE DATOS

CREATE TABLE LIBROS(
ID_LIBRO INT NOT NULL auto_increment primary KEY,
ISBN VARCHAR(15) NOT NULL, 
EDITORIAL VARCHAR(15),
CANTIDAD INT  NOT NULL,
PRECIO INT NOT NULL
);